image: phlummox/android-studio:latest
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    protocol: "http"

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
